version: "3.1"

services:
  web:
    image: webdevops/php-apache:8.0
    ports:
      - "8000:80"
    volumes:
    - ./www:/app


  db:
    image: mysql
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - 8081:3306
    environment:
      MYSQL_USER: admin
      MYSQL_DATABASE: sistema_entregas
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
      
    ports:
      - "8080:80"
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
